SELECT CUSTOMER_ID,COUNT(COUNT_NO_TRANS) AS COUNT_NO_TRANS
FROM (

    SELECT V.CUSTOMER_ID, 
        CASE WHEN V.VISIT_ID = T.VISIT_ID THEN NULL
             ELSE COUNT(V.VISIT_ID) OVER (PARTITION BY V.CUSTOMER_ID) 
        END  AS COUNT_NO_TRANS
    FROM VISITS V
    LEFT JOIN Transactions T ON V.VISIT_ID = T.VISIT_ID

)A 
WHERE COUNT_NO_TRANS IS NOT NULL
GROUP BY CUSTOMER_ID
ORDER BY COUNT_NO_TRANS